### ISSUE TITLE
Toggling night-mode resets to latest article

### ISSUE THREAD

**Issue by evelikov** [tom-anders/Easy_xkcd#262] opened 2021-05-24 17:16 UTC
This is my last night-mode bugreport I promise ;-)

When switching on/off the night-mode via the hamburger menu, the app resets to the last article. On the other hand changing it via settings works just fine. So it seems like we're preserving the number/index in the latter case but no the former.

**Comment by tom-anders** [comment] 2021-05-24 19:34
Hmm I can't reproduce this one. Can you reproduce it 100% or does it only happen sometimes?

**Comment by evelikov** [comment] 2021-05-31 08:30
It's 100% reproducible, although my original report is off - one needs to toggle night mode twice (off-on-off or on-off-on)
 - open app, go to random XKCD article
 - press the hamburger menu and toggle `Night mode`
 - you're still on the original article
 - press the hamburger menu and toggle `Night mode`
 - you're sent to the latest article

**Comment by tom-anders** [comment] 2021-05-31 08:43
Ah yeah, now I can reproduce it as well. Will take a look.

**Comment by tom-anders** [comment] 2022-04-09 09:38
Fixed in the beta (and also the upcoming 8.0 release)

**Closed by tom-anders** 2022-04-09 09:38 UTC
Labels: bug
