### ISSUE TITLE
What If? tab broken

### ISSUE THREAD

**Issue by Aelar64** [tom-anders/Easy_xkcd#301] opened 2022-05-08 17:06 UTC
When navigating to the what if? tab, only three articles sure up, and they have incorrect numbers and titles. It looks like a problem from when Randall changed the site around to promote the new book.

Running app version 8.0.4, which appears to be the latest release from the Play store

Screenshot:
![Screenshot_20220508-100448_Easy xkcd](https://user-images.githubusercontent.com/16154848/167307205-52377ae9-72a8-48e9-b5df-981bed6e6a13.png)

**Comment by jerbear2008** [comment] 2022-07-08 16:28
Same problem, on the latest from F-Droid

**Comment by tom-anders** [comment] 2023-10-03 10:47
Sorry for the late answer, this was caused by a redesign of the what-if website, the App has already been adapted in https://github.com/tom-anders/Easy_xkcd/commit/f713fcc9ab176e1410fbd27c3974e6f45f967657 so I'll close this issue.

**Closed by tom-anders** 2023-10-03 10:47 UTC
